version: "3.8"

services:
  express-app:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: express-app

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: --interval 60 express-app